dist: xenial

language: python

python:
  - 3.7

install:
  - pip install -r test-requirements.txt

script:
  - py.test
  - mypy usbmon tools
  - python setup.py bdist_wheel
  - pip install ./dist/usbmon_tools-*.whl
