dist: xenial

language: python

matrix:
  include:
    - python: 3.7
      env: PRE_COMMIT=true
    - python: 3.8

install:
  - pip install .[dev]

script:
  - py.test -vvv
  - mypy usbmon tools
  - python setup.py bdist_wheel
  - pip install ./dist/usbmon_tools-*.whl
  - if [[ $PRE_COMMIT ]]; then pre-commit install; pre-commit run --all-files; fi
